model_list:
#Bedrock Models
  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0

  - model_name: us.amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v2:0

