model_list:
#Bedrock Models
  - model_name: amazon.titan-tg1-large
    litellm_params:
      model: bedrock/amazon.titan-tg1-large

  - model_name: amazon.titan-embed-g1-text-02
    litellm_params:
      model: bedrock/amazon.titan-embed-g1-text-02

  - model_name: amazon.titan-text-lite-v1
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1

  - model_name: amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1

  - model_name: amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1
      drop_params: true #Needed to avoid errors when encoding_format is passed in by openai python client

  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0
      drop_params: true #Needed to avoid errors when encoding_format is passed in by openai python client

  - model_name: amazon.titan-embed-image-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-image-v1
      drop_params: true #Needed to avoid errors when encoding_format is passed in by openai python client

  - model_name: amazon.titan-image-generator-v1
    litellm_params:
      model: bedrock/amazon.titan-image-generator-v1

  - model_name: amazon.titan-image-generator-v2:0
    litellm_params:
      model: bedrock/amazon.titan-image-generator-v2:0

  - model_name: amazon.rerank-v1:0
    litellm_params:
      model: bedrock/amazon.rerank-v1:0

  - model_name: stability.sd3-5-large-v1:0
    litellm_params:
      model: bedrock/stability.sd3-5-large-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: anthropic.claude-3-5-haiku-20241022-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-haiku-20241022-v1:0

  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: anthropic.claude-3-opus-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: cohere.command-text-v14
    litellm_params:
      model: bedrock/cohere.command-text-v14

  - model_name: cohere.command-r-v1:0
    litellm_params:
      model: bedrock/cohere.command-r-v1:0

  - model_name: cohere.command-r-plus-v1:0
    litellm_params:
      model: bedrock/cohere.command-r-plus-v1:0

  - model_name: cohere.command-light-text-v14
    litellm_params:
      model: bedrock/cohere.command-light-text-v14

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3
      drop_params: true #Needed to avoid errors when encoding_format is passed in by openai python client

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: cohere.rerank-v3-5:0
    litellm_params:
      model: bedrock/cohere.rerank-v3-5:0

  - model_name: meta.llama3-8b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-8b-instruct-v1:0

  - model_name: meta.llama3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-70b-instruct-v1:0

  - model_name: meta.llama3-1-8b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-1-8b-instruct-v1:0

  - model_name: meta.llama3-1-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-1-70b-instruct-v1:0

  - model_name: meta.llama3-1-405b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-1-405b-instruct-v1:0

  - model_name: mistral.mistral-7b-instruct-v0:2
    litellm_params:
      model: bedrock/mistral.mistral-7b-instruct-v0:2

  - model_name: mistral.mixtral-8x7b-instruct-v0:1
    litellm_params:
      model: bedrock/mistral.mixtral-8x7b-instruct-v0:1

  - model_name: mistral.mistral-large-2402-v1:0
    litellm_params:
      model: bedrock/mistral.mistral-large-2402-v1:0

  - model_name: mistral.mistral-large-2407-v1:0
    litellm_params:
      model: bedrock/mistral.mistral-large-2407-v1:0

  - model_name: luma.ray-v2:0
    litellm_params:
      model: bedrock/luma.ray-v2:0

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: us.anthropic.claude-3-opus-20240229-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-opus-20240229-v1:0

  - model_name: us.meta.llama3-2-11b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-11b-instruct-v1:0

  - model_name: us.meta.llama3-2-90b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-90b-instruct-v1:0

  - model_name: us.meta.llama3-2-3b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-3b-instruct-v1:0

  - model_name: us.meta.llama3-2-1b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-1b-instruct-v1:0

  - model_name: us.anthropic.claude-3-5-haiku-20241022-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0

  - model_name: us.meta.llama3-1-8b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-8b-instruct-v1:0

  - model_name: us.meta.llama3-1-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-70b-instruct-v1:0

  - model_name: us.amazon.nova-pro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-pro-v1:0

  - model_name: us.amazon.nova-lite-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-lite-v1:0

  - model_name: us.amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-micro-v1:0

  - model_name: us.meta.llama3-3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-3-70b-instruct-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: us.anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0