model_list:
#Bedrock Models
  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3
      drop_params: true #Needed to avoid errors when encoding_format is passed in by openai python client

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: apac.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: apac.anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: apac.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: apac.anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-5-sonnet-20241022-v2:0

