model_list:
#Bedrock Models
  - model_name: anthropic.claude-instant-v1:2
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1:2

  - model_name: us.anthropic.claude-instant-v1:2
    litellm_params:
      model: bedrock/us.anthropic.claude-instant-v1:2

  - model_name: anthropic.claude-instant-v1
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1

  - model_name: us.anthropic.claude-instant-v1
    litellm_params:
      model: bedrock/us.anthropic.claude-instant-v1

  - model_name: anthropic.claude-v2:0
    litellm_params:
      model: bedrock/anthropic.claude-v2:0

  - model_name: us.anthropic.claude-v2:0
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:0

  - model_name: anthropic.claude-v2
    litellm_params:
      model: bedrock/anthropic.claude-v2

  - model_name: us.anthropic.claude-v2
    litellm_params:
      model: bedrock/us.anthropic.claude-v2

  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0:28k
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0:28k

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0:28k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0:28k

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0:200k
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0:200k

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0:200k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0:200k

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: us.anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3

  - model_name: us.cohere.embed-english-v3
    litellm_params:
      model: bedrock/us.cohere.embed-english-v3

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: us.cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/us.cohere.embed-multilingual-v3

