model_list:
#Bedrock Models
  - model_name: amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1

  - model_name: amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1

  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0

  - model_name: amazon.rerank-v1:0
    litellm_params:
      model: bedrock/amazon.rerank-v1:0

  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: cohere.rerank-v3-5:0
    litellm_params:
      model: bedrock/cohere.rerank-v3-5:0

  - model_name: apac.anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: apac.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: apac.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: apac.anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/apac.anthropic.claude-3-5-sonnet-20241022-v2:0

