model_list:
#Bedrock Models
  - model_name: amazon.titan-tg1-large
    litellm_params:
      model: bedrock/amazon.titan-tg1-large

  - model_name: us.amazon.titan-tg1-large
    litellm_params:
      model: bedrock/us.amazon.titan-tg1-large

  - model_name: amazon.titan-image-generator-v1:0
    litellm_params:
      model: bedrock/amazon.titan-image-generator-v1:0

  - model_name: us.amazon.titan-image-generator-v1:0
    litellm_params:
      model: bedrock/us.amazon.titan-image-generator-v1:0

  - model_name: amazon.titan-image-generator-v1
    litellm_params:
      model: bedrock/amazon.titan-image-generator-v1

  - model_name: us.amazon.titan-image-generator-v1
    litellm_params:
      model: bedrock/us.amazon.titan-image-generator-v1

  - model_name: amazon.titan-image-generator-v2:0
    litellm_params:
      model: bedrock/amazon.titan-image-generator-v2:0

  - model_name: us.amazon.titan-image-generator-v2:0
    litellm_params:
      model: bedrock/us.amazon.titan-image-generator-v2:0

  - model_name: amazon.titan-text-premier-v1:0
    litellm_params:
      model: bedrock/amazon.titan-text-premier-v1:0

  - model_name: us.amazon.titan-text-premier-v1:0
    litellm_params:
      model: bedrock/us.amazon.titan-text-premier-v1:0

  - model_name: amazon.nova-pro-v1:0:300k
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0:300k

  - model_name: us.amazon.nova-pro-v1:0:300k
    litellm_params:
      model: bedrock/us.amazon.nova-pro-v1:0:300k

  - model_name: amazon.nova-pro-v1:0
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0

  - model_name: us.amazon.nova-pro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-pro-v1:0

  - model_name: amazon.nova-lite-v1:0:300k
    litellm_params:
      model: bedrock/amazon.nova-lite-v1:0:300k

  - model_name: us.amazon.nova-lite-v1:0:300k
    litellm_params:
      model: bedrock/us.amazon.nova-lite-v1:0:300k

  - model_name: amazon.nova-lite-v1:0
    litellm_params:
      model: bedrock/amazon.nova-lite-v1:0

  - model_name: us.amazon.nova-lite-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-lite-v1:0

  - model_name: amazon.nova-canvas-v1:0
    litellm_params:
      model: bedrock/amazon.nova-canvas-v1:0

  - model_name: us.amazon.nova-canvas-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-canvas-v1:0

  - model_name: amazon.nova-reel-v1:0
    litellm_params:
      model: bedrock/amazon.nova-reel-v1:0

  - model_name: us.amazon.nova-reel-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-reel-v1:0

  - model_name: amazon.nova-micro-v1:0:128k
    litellm_params:
      model: bedrock/amazon.nova-micro-v1:0:128k

  - model_name: us.amazon.nova-micro-v1:0:128k
    litellm_params:
      model: bedrock/us.amazon.nova-micro-v1:0:128k

  - model_name: amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/amazon.nova-micro-v1:0

  - model_name: us.amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-micro-v1:0

  - model_name: amazon.titan-embed-g1-text-02
    litellm_params:
      model: bedrock/amazon.titan-embed-g1-text-02

  - model_name: us.amazon.titan-embed-g1-text-02
    litellm_params:
      model: bedrock/us.amazon.titan-embed-g1-text-02

  - model_name: amazon.titan-text-lite-v1:0:4k
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1:0:4k

  - model_name: us.amazon.titan-text-lite-v1:0:4k
    litellm_params:
      model: bedrock/us.amazon.titan-text-lite-v1:0:4k

  - model_name: amazon.titan-text-lite-v1
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1

  - model_name: us.amazon.titan-text-lite-v1
    litellm_params:
      model: bedrock/us.amazon.titan-text-lite-v1

  - model_name: amazon.titan-text-express-v1:0:8k
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1:0:8k

  - model_name: us.amazon.titan-text-express-v1:0:8k
    litellm_params:
      model: bedrock/us.amazon.titan-text-express-v1:0:8k

  - model_name: amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1

  - model_name: us.amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/us.amazon.titan-text-express-v1

  - model_name: amazon.titan-embed-text-v1:2:8k
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1:2:8k

  - model_name: us.amazon.titan-embed-text-v1:2:8k
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v1:2:8k

  - model_name: amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1

  - model_name: us.amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v1

  - model_name: amazon.titan-embed-text-v2:0:8k
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0:8k

  - model_name: us.amazon.titan-embed-text-v2:0:8k
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v2:0:8k

  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0

  - model_name: us.amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v2:0

  - model_name: stability.stable-diffusion-xl-v1:0
    litellm_params:
      model: bedrock/stability.stable-diffusion-xl-v1:0

  - model_name: us.stability.stable-diffusion-xl-v1:0
    litellm_params:
      model: bedrock/us.stability.stable-diffusion-xl-v1:0

  - model_name: stability.stable-diffusion-xl-v1
    litellm_params:
      model: bedrock/stability.stable-diffusion-xl-v1

  - model_name: us.stability.stable-diffusion-xl-v1
    litellm_params:
      model: bedrock/us.stability.stable-diffusion-xl-v1

  - model_name: ai21.j2-grande-instruct
    litellm_params:
      model: bedrock/ai21.j2-grande-instruct

  - model_name: us.ai21.j2-grande-instruct
    litellm_params:
      model: bedrock/us.ai21.j2-grande-instruct

  - model_name: ai21.j2-jumbo-instruct
    litellm_params:
      model: bedrock/ai21.j2-jumbo-instruct

  - model_name: us.ai21.j2-jumbo-instruct
    litellm_params:
      model: bedrock/us.ai21.j2-jumbo-instruct

  - model_name: ai21.j2-mid
    litellm_params:
      model: bedrock/ai21.j2-mid

  - model_name: us.ai21.j2-mid
    litellm_params:
      model: bedrock/us.ai21.j2-mid

  - model_name: ai21.j2-mid-v1
    litellm_params:
      model: bedrock/ai21.j2-mid-v1

  - model_name: us.ai21.j2-mid-v1
    litellm_params:
      model: bedrock/us.ai21.j2-mid-v1

  - model_name: ai21.j2-ultra
    litellm_params:
      model: bedrock/ai21.j2-ultra

  - model_name: us.ai21.j2-ultra
    litellm_params:
      model: bedrock/us.ai21.j2-ultra

  - model_name: ai21.j2-ultra-v1:0:8k
    litellm_params:
      model: bedrock/ai21.j2-ultra-v1:0:8k

  - model_name: us.ai21.j2-ultra-v1:0:8k
    litellm_params:
      model: bedrock/us.ai21.j2-ultra-v1:0:8k

  - model_name: ai21.j2-ultra-v1
    litellm_params:
      model: bedrock/ai21.j2-ultra-v1

  - model_name: us.ai21.j2-ultra-v1
    litellm_params:
      model: bedrock/us.ai21.j2-ultra-v1

  - model_name: ai21.jamba-instruct-v1:0
    litellm_params:
      model: bedrock/ai21.jamba-instruct-v1:0

  - model_name: us.ai21.jamba-instruct-v1:0
    litellm_params:
      model: bedrock/us.ai21.jamba-instruct-v1:0

  - model_name: ai21.jamba-1-5-large-v1:0
    litellm_params:
      model: bedrock/ai21.jamba-1-5-large-v1:0

  - model_name: us.ai21.jamba-1-5-large-v1:0
    litellm_params:
      model: bedrock/us.ai21.jamba-1-5-large-v1:0

  - model_name: ai21.jamba-1-5-mini-v1:0
    litellm_params:
      model: bedrock/ai21.jamba-1-5-mini-v1:0

  - model_name: us.ai21.jamba-1-5-mini-v1:0
    litellm_params:
      model: bedrock/us.ai21.jamba-1-5-mini-v1:0

  - model_name: anthropic.claude-instant-v1:2:100k
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1:2:100k

  - model_name: us.anthropic.claude-instant-v1:2:100k
    litellm_params:
      model: bedrock/us.anthropic.claude-instant-v1:2:100k

  - model_name: anthropic.claude-instant-v1
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1

  - model_name: us.anthropic.claude-instant-v1
    litellm_params:
      model: bedrock/us.anthropic.claude-instant-v1

  - model_name: anthropic.claude-v2:0:18k
    litellm_params:
      model: bedrock/anthropic.claude-v2:0:18k

  - model_name: us.anthropic.claude-v2:0:18k
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:0:18k

  - model_name: anthropic.claude-v2:0:100k
    litellm_params:
      model: bedrock/anthropic.claude-v2:0:100k

  - model_name: us.anthropic.claude-v2:0:100k
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:0:100k

  - model_name: anthropic.claude-v2:1:18k
    litellm_params:
      model: bedrock/anthropic.claude-v2:1:18k

  - model_name: us.anthropic.claude-v2:1:18k
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:1:18k

  - model_name: anthropic.claude-v2:1:200k
    litellm_params:
      model: bedrock/anthropic.claude-v2:1:200k

  - model_name: us.anthropic.claude-v2:1:200k
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:1:200k

  - model_name: anthropic.claude-v2:1
    litellm_params:
      model: bedrock/anthropic.claude-v2:1

  - model_name: us.anthropic.claude-v2:1
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:1

  - model_name: anthropic.claude-v2
    litellm_params:
      model: bedrock/anthropic.claude-v2

  - model_name: us.anthropic.claude-v2
    litellm_params:
      model: bedrock/us.anthropic.claude-v2

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0:28k
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0:28k

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0:28k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0:28k

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0:200k
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0:200k

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0:200k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0:200k

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: anthropic.claude-3-haiku-20240307-v1:0:48k
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0:48k

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0:48k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0:48k

  - model_name: anthropic.claude-3-haiku-20240307-v1:0:200k
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0:200k

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0:200k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0:200k

  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: anthropic.claude-3-opus-20240229-v1:0:12k
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0:12k

  - model_name: us.anthropic.claude-3-opus-20240229-v1:0:12k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-opus-20240229-v1:0:12k

  - model_name: anthropic.claude-3-opus-20240229-v1:0:28k
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0:28k

  - model_name: us.anthropic.claude-3-opus-20240229-v1:0:28k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-opus-20240229-v1:0:28k

  - model_name: anthropic.claude-3-opus-20240229-v1:0:200k
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0:200k

  - model_name: us.anthropic.claude-3-opus-20240229-v1:0:200k
    litellm_params:
      model: bedrock/us.anthropic.claude-3-opus-20240229-v1:0:200k

  - model_name: anthropic.claude-3-opus-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0

  - model_name: us.anthropic.claude-3-opus-20240229-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-opus-20240229-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: us.anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: anthropic.claude-3-5-haiku-20241022-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-haiku-20241022-v1:0

  - model_name: us.anthropic.claude-3-5-haiku-20241022-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0

  - model_name: cohere.command-text-v14:7:4k
    litellm_params:
      model: bedrock/cohere.command-text-v14:7:4k

  - model_name: us.cohere.command-text-v14:7:4k
    litellm_params:
      model: bedrock/us.cohere.command-text-v14:7:4k

  - model_name: cohere.command-text-v14
    litellm_params:
      model: bedrock/cohere.command-text-v14

  - model_name: us.cohere.command-text-v14
    litellm_params:
      model: bedrock/us.cohere.command-text-v14

  - model_name: cohere.command-r-v1:0
    litellm_params:
      model: bedrock/cohere.command-r-v1:0

  - model_name: us.cohere.command-r-v1:0
    litellm_params:
      model: bedrock/us.cohere.command-r-v1:0

  - model_name: cohere.command-r-plus-v1:0
    litellm_params:
      model: bedrock/cohere.command-r-plus-v1:0

  - model_name: us.cohere.command-r-plus-v1:0
    litellm_params:
      model: bedrock/us.cohere.command-r-plus-v1:0

  - model_name: cohere.command-light-text-v14:7:4k
    litellm_params:
      model: bedrock/cohere.command-light-text-v14:7:4k

  - model_name: us.cohere.command-light-text-v14:7:4k
    litellm_params:
      model: bedrock/us.cohere.command-light-text-v14:7:4k

  - model_name: cohere.command-light-text-v14
    litellm_params:
      model: bedrock/cohere.command-light-text-v14

  - model_name: us.cohere.command-light-text-v14
    litellm_params:
      model: bedrock/us.cohere.command-light-text-v14

  - model_name: cohere.embed-english-v3:0:512
    litellm_params:
      model: bedrock/cohere.embed-english-v3:0:512

  - model_name: us.cohere.embed-english-v3:0:512
    litellm_params:
      model: bedrock/us.cohere.embed-english-v3:0:512

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3

  - model_name: us.cohere.embed-english-v3
    litellm_params:
      model: bedrock/us.cohere.embed-english-v3

  - model_name: cohere.embed-multilingual-v3:0:512
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3:0:512

  - model_name: us.cohere.embed-multilingual-v3:0:512
    litellm_params:
      model: bedrock/us.cohere.embed-multilingual-v3:0:512

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: us.cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/us.cohere.embed-multilingual-v3

  - model_name: meta.llama3-8b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-8b-instruct-v1:0

  - model_name: us.meta.llama3-8b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-8b-instruct-v1:0

  - model_name: meta.llama3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-70b-instruct-v1:0

  - model_name: us.meta.llama3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-70b-instruct-v1:0

  - model_name: meta.llama3-1-8b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-1-8b-instruct-v1:0

  - model_name: us.meta.llama3-1-8b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-8b-instruct-v1:0

  - model_name: meta.llama3-1-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-1-70b-instruct-v1:0

  - model_name: us.meta.llama3-1-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-70b-instruct-v1:0

  - model_name: meta.llama3-2-11b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-2-11b-instruct-v1:0

  - model_name: us.meta.llama3-2-11b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-11b-instruct-v1:0

  - model_name: meta.llama3-2-90b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-2-90b-instruct-v1:0

  - model_name: us.meta.llama3-2-90b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-90b-instruct-v1:0

  - model_name: meta.llama3-2-1b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-2-1b-instruct-v1:0

  - model_name: us.meta.llama3-2-1b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-1b-instruct-v1:0

  - model_name: meta.llama3-2-3b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-2-3b-instruct-v1:0

  - model_name: us.meta.llama3-2-3b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-3b-instruct-v1:0

  - model_name: meta.llama3-3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-3-70b-instruct-v1:0

  - model_name: us.meta.llama3-3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-3-70b-instruct-v1:0

  - model_name: mistral.mistral-7b-instruct-v0:2
    litellm_params:
      model: bedrock/mistral.mistral-7b-instruct-v0:2

  - model_name: us.mistral.mistral-7b-instruct-v0:2
    litellm_params:
      model: bedrock/us.mistral.mistral-7b-instruct-v0:2

  - model_name: mistral.mixtral-8x7b-instruct-v0:1
    litellm_params:
      model: bedrock/mistral.mixtral-8x7b-instruct-v0:1

  - model_name: us.mistral.mixtral-8x7b-instruct-v0:1
    litellm_params:
      model: bedrock/us.mistral.mixtral-8x7b-instruct-v0:1

  - model_name: mistral.mistral-large-2402-v1:0
    litellm_params:
      model: bedrock/mistral.mistral-large-2402-v1:0

  - model_name: us.mistral.mistral-large-2402-v1:0
    litellm_params:
      model: bedrock/us.mistral.mistral-large-2402-v1:0

  - model_name: mistral.mistral-small-2402-v1:0
    litellm_params:
      model: bedrock/mistral.mistral-small-2402-v1:0

  - model_name: us.mistral.mistral-small-2402-v1:0
    litellm_params:
      model: bedrock/us.mistral.mistral-small-2402-v1:0

