model_list:
#Bedrock Models
  - model_name: amazon.titan-text-express-v1:0:8k
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1:0:8k

  - model_name: us.amazon.titan-text-express-v1:0:8k
    litellm_params:
      model: bedrock/us.amazon.titan-text-express-v1:0:8k

  - model_name: amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1

  - model_name: us.amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/us.amazon.titan-text-express-v1

  - model_name: amazon.titan-text-lite-v1:0:4k
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1:0:4k

  - model_name: us.amazon.titan-text-lite-v1:0:4k
    litellm_params:
      model: bedrock/us.amazon.titan-text-lite-v1:0:4k

  - model_name: amazon.titan-text-lite-v1
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1

  - model_name: us.amazon.titan-text-lite-v1
    litellm_params:
      model: bedrock/us.amazon.titan-text-lite-v1

  - model_name: amazon.titan-embed-text-v1:2:8k
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1:2:8k

  - model_name: us.amazon.titan-embed-text-v1:2:8k
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v1:2:8k

  - model_name: amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1

  - model_name: us.amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v1

  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0

  - model_name: us.amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/us.amazon.titan-embed-text-v2:0

  - model_name: amazon.rerank-v1:0
    litellm_params:
      model: bedrock/amazon.rerank-v1:0

  - model_name: us.amazon.rerank-v1:0
    litellm_params:
      model: bedrock/us.amazon.rerank-v1:0

  - model_name: anthropic.claude-instant-v1
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1

  - model_name: us.anthropic.claude-instant-v1
    litellm_params:
      model: bedrock/us.anthropic.claude-instant-v1

  - model_name: anthropic.claude-v2:1:18k
    litellm_params:
      model: bedrock/anthropic.claude-v2:1:18k

  - model_name: us.anthropic.claude-v2:1:18k
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:1:18k

  - model_name: anthropic.claude-v2:1:200k
    litellm_params:
      model: bedrock/anthropic.claude-v2:1:200k

  - model_name: us.anthropic.claude-v2:1:200k
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:1:200k

  - model_name: anthropic.claude-v2:1
    litellm_params:
      model: bedrock/anthropic.claude-v2:1

  - model_name: us.anthropic.claude-v2:1
    litellm_params:
      model: bedrock/us.anthropic.claude-v2:1

  - model_name: anthropic.claude-v2
    litellm_params:
      model: bedrock/anthropic.claude-v2

  - model_name: us.anthropic.claude-v2
    litellm_params:
      model: bedrock/us.anthropic.claude-v2

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: us.anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3

  - model_name: us.cohere.embed-english-v3
    litellm_params:
      model: bedrock/us.cohere.embed-english-v3

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: us.cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/us.cohere.embed-multilingual-v3

  - model_name: cohere.rerank-v3-5:0
    litellm_params:
      model: bedrock/cohere.rerank-v3-5:0

  - model_name: us.cohere.rerank-v3-5:0
    litellm_params:
      model: bedrock/us.cohere.rerank-v3-5:0

  - model_name: meta.llama3-2-1b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-2-1b-instruct-v1:0

  - model_name: us.meta.llama3-2-1b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-1b-instruct-v1:0

  - model_name: meta.llama3-2-3b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-2-3b-instruct-v1:0

  - model_name: us.meta.llama3-2-3b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-3b-instruct-v1:0

